version: "3.8"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=tolqin
        ports:
            - 5432:5432
        command: ["-c", "log_statement=all"]
