name: Lint, Test & Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  api-lint:
    name: "api: Run linters"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Change directory
      run: cd app/api
        
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

  api-unit-test:
    name: "api: Run unit tests"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Change directory
      run: cd app/api
        
    - name: Run unit tests
      run: go test --covermode=count ./...

  api-build-test:
    name: "api: Test build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Change directory
      run: cd app/api
        
    - name: Build
      run: go build cmd/tolqin-api/main.go
