name: Lint, Test, Build & Publish

on:
  push:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Run unit tests
      run: go test --covermode=count ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Build
      run: go build cmd/tolqin-api/main.go

  publish:
    needs: [lint, unit-test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push image to DockerHub
      run: ./scripts/publish.sh ${{ secrets.DOCKERHUB_REPOSITORY }}
